class Player:
	def __init__(self, server, channel):
		self.server = server
		self.channel = channel
		self.users = server.users

		self.langue = ""
		self.langueID = 0
		self.link = ""
		self.captcha = ""
		self.playerID = 0
		self.playerName = ""
		self.playerTag = ""
		self.privLevel = 0
		self.playingTime = 0
		self.playerScore = 0
		self.shamanType = 0
		self.shamanLevel = 0
		self.shamanExp = 0
		self.shamanExpNext = 0
		self.Badge = 0
		self.titleID = 0.1
		self.gender = 0
		self.regDate = 0
		self.colorNick = ""
		self.playerLook = "1;0,0,0,0,0,0,0,0,0,0,0"
		self.shamanLook = "0,0,0,0,0,0,0,0,0,0"
		self.mouseColor = "78583a"
		self.shamanColor = "95d9d6"
		self.marriage = ""
		self.shopItems = []
		self.playerPing = [0, 0]
		self.survivorStats = [0, 0, 0, 0]
		self.racingStats = [0, 0, 0, 0]
		self.isMovingRight = False
		self.isMovingLeft = False
		self.hasEnter = False
		self.currentPlace = 0
		self.posX = 0
		self.posY = 0
		self.velX = 0
		self.velY = 0
		self.roomsListMode = 0
		self.playerStartTimeMillis = 0
		self.connectedTime = 0
		self.shopCheeses = 500000
		self.shopFraises = 500000
		self.cheeseCount = 0
		self.firstCount = 0
		self.bootcampCount = 0
		self.shamanSaves = 0
		self.shamanCheeses = 0
		self.hardModeSaves = 0
		self.divineModeSaves = 0
		self.playerSkills = {}
		self.lastChatMessage = ""
		self.lastChatMessageTime = 0
		self.spamConsiderations = 0
		self.censuredChat = False
		self.privsList = []
		self.titlesList = [0.1]
		self.shopBadges = []
		self.shamanBadges = []
		self.equipedShamanBadge = []
		self.adventurePoints = 0
		self.clothes = []
		self.shamanItems = []
		self.canShamanRespawn = False
		self.isJumping = False
		self.isShaman = False
		self.isLogged = False
		self.isDead = False
		self.hasCheese = False
		self.isAfk = True
		self.lastAfkTime = 0
		self.isSync = False
		self.isFuncorp = False
		self.isLuacrew = False
		self.isMapcrew = False
		self.isNewPlayer = False
		self.isVampire = False
		self.isOpportunist = False
		self.iceCount = 0
		self.desintegration = False
		self.friendsList = []
		self.ignoredsList = []
		self.friendsOpen = False
		self.lastLogin = 0
		self.marriageInvite = ""
		self.whisperTime = 0
		self.whisperCount = 0
		self.silenceType = 0
		self.silenceMessage = ""
		self.chats = []
		self.modoPwet = False
		self.modoPwetLangue = "ALL"
		self.isHide = False
		self.lastMovimentTime = 0
		self.roundsPlayed = 0
		self.isVip = False
		self.cAwards = 0
		self.modoPwetNotification = False
		self.karmas = 0
		self.loginXor = 0
		self.referrals = 0
		self.missions = {
			1: [0, 0, 10, 32, False],
			3: [0, 0, 1, 32, False],
			50: [0, 0, 1, 32, False],
			51: [0, 0, 1, 32, False],
			52: [0, 0, 1, 32, False]
		}
		self.seasonMessage = True
		self.seasonFirstCount = 0
		self.seasonCheeseCount = 0
		self.seasonSavesCount = 0
		self.lastDummyTime = 0
		self.isStandAlone = False
		self.playerConsumables = {}
		self.equipedConsumables = []
		self.chatLog = {"room": [], "whisper": {}}
		self.funColor = ""
		self.funMouseColor = ""

		self.room = None
		self.tribe = None